nelmio_cors:
    defaults:
        allow_origin: [
            'https://front-ecoactivities-ltm6.vercel.app',
             'https://www.ecoactivities.fr',
             'https://ecoactivities.fr'  
        ]
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: [
                'https://front-ecoactivities-ltm6.vercel.app',
                'https://ecoactivities.fr',
                'https://www.ecoactivities.fr'


                ]
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600


