security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Authentification par login (JWT)
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Routes API protégées par token JWT
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        # Routes publiques si besoin
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
     # Inscription
    - { path: ^/api/users/create, roles: PUBLIC_ACCESS }

    # Login JWT
    - { path: ^/api/login_check, roles: PUBLIC_ACCESS }

    - { path: ^/api/logout$, roles: IS_AUTHENTICATED_FULLY }

    # Activités accessibles publiquement
    - { path: ^/api/activities, roles: PUBLIC_ACCESS }

    # Voir ses propres infos
    - { path: ^/api/users/me$, roles: ROLE_USER }

    # Modifier ou supprimer son propre compte
    - { path: ^/api/users/\d+$, roles: ROLE_USER }

    # Admin peut aussi accéder à tous les comptes
    - { path: ^/api/users/\d+$, roles: ROLE_ADMIN }

    # Admin peut modifier les rôles
    - { path: ^/api/users/\d+/roles$, roles: ROLE_ADMIN }

    # Lister tous les utilisateurs
    - { path: ^/api/users$, roles: ROLE_ADMIN }

    # Routes d'administration générales
    - { path: ^/api/admin, roles: ROLE_ADMIN }

    # Toute autre route API nécessite un token valide (optionnel)
    # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }